/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulp.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadulp.accesoADatos.*;
import universidadulp.entidades.*;

/**
 *
 * @author marti
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {

    private AlumnoData ad = new AlumnoData();
    private InscripcionData ID = new InscripcionData();
    private List<Materia> materias = new ArrayList<>();
    private List<Alumno> alumnos;
    private MateriaData MD = new MateriaData();
    private DefaultTableModel jInscripcion = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion() {
        initComponents();
        cabecera();
        armarComboB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrMateriasNoInscriptas = new javax.swing.JRadioButton();
        jrMateriasInscriptas = new javax.swing.JRadioButton();
        jbInscribir = new javax.swing.JButton();
        jbAnularInscripcion = new javax.swing.JButton();
        jbSalirInscripcion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtInscripcion = new javax.swing.JTable();
        jcAlumnoSeleccionado = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("FORMULARIO INSCRIPCION");

        jLabel2.setText("Seleccionar un Alumno");

        jLabel3.setText("Listado de Materias");

        buttonGroup1.add(jrMateriasNoInscriptas);
        jrMateriasNoInscriptas.setText("Materias no Inscriptas");
        jrMateriasNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateriasNoInscriptasActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMateriasInscriptas);
        jrMateriasInscriptas.setText("Materias Inscriptas");
        jrMateriasInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateriasInscriptasActionPerformed(evt);
            }
        });

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularInscripcion.setText("Anular Inscripcion");
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });

        jbSalirInscripcion.setText("Salir");
        jbSalirInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirInscripcionActionPerformed(evt);
            }
        });

        jtInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtInscripcion);

        jcAlumnoSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAlumnoSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jcAlumnoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrMateriasInscriptas)
                                .addGap(102, 102, 102)
                                .addComponent(jrMateriasNoInscriptas)))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbInscribir)
                        .addGap(18, 18, 18)
                        .addComponent(jbAnularInscripcion)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalirInscripcion)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcAlumnoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMateriasNoInscriptas)
                    .addComponent(jrMateriasInscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalirInscripcion)
                    .addComponent(jbAnularInscripcion)
                    .addComponent(jbInscribir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed

        int fila = jtInscripcion.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una materia para anular su inscripción.");
        } else {
            Alumno alumno = (Alumno) jcAlumnoSeleccionado.getModel().getSelectedItem();
            int id = (int) jInscripcion.getValueAt(jtInscripcion.getSelectedRow(), 0);
            ID.borrarInscripcionMateriaAlumno(alumno.getIdAlumno(), id);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed

        int fila = jtInscripcion.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una materia para inscribir al alumno.");
        } else {
            Alumno alumno = (Alumno) jcAlumnoSeleccionado.getModel().getSelectedItem();
            int id = (int) jInscripcion.getValueAt(jtInscripcion.getSelectedRow(), 0);
            Materia mate = MD.buscarMateria(id);

            Inscripcion insc = new Inscripcion();
            insc.setAlumno(alumno);
            insc.setMateria(mate);

            ID.guardarInscripcion(insc);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbSalirInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirInscripcionActionPerformed

        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirInscripcionActionPerformed

    private void jrMateriasInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateriasInscriptasActionPerformed
        if (jrMateriasInscriptas.isSelected()) {
            jbAnularInscripcion.setEnabled(true);
            jbInscribir.setEnabled(false);
        }
        borrarFilas();
        Alumno alum = (Alumno) jcAlumnoSeleccionado.getModel().getSelectedItem();
        materias = ID.obtenerMateriasCursadas(alum.getIdAlumno());
        for (Materia mate : materias) {

            jInscripcion.addRow(new Object[]{
                mate.getIdMateria(),
                mate.getNombre(),
                mate.getAnioMateria()});

        }
    }//GEN-LAST:event_jrMateriasInscriptasActionPerformed

    private void jrMateriasNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateriasNoInscriptasActionPerformed
        if (jrMateriasNoInscriptas.isSelected()) {
            jbAnularInscripcion.setEnabled(false);
            jbInscribir.setEnabled(true);
        }
        borrarFilas();
        Alumno alum = (Alumno) jcAlumnoSeleccionado.getModel().getSelectedItem();
        materias = ID.obtenerMateriasNoCursadas(alum.getIdAlumno());
        for (Materia mate : materias) {

            jInscripcion.addRow(new Object[]{
                mate.getIdMateria(),
                mate.getNombre(),
                mate.getAnioMateria()});

        }
    }//GEN-LAST:event_jrMateriasNoInscriptasActionPerformed

    private void jcAlumnoSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAlumnoSeleccionadoActionPerformed
        // TODO add your handling code here:
        borrarFilas();
    }//GEN-LAST:event_jcAlumnoSeleccionadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAnularInscripcion;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalirInscripcion;
    private javax.swing.JComboBox<Alumno> jcAlumnoSeleccionado;
    private javax.swing.JRadioButton jrMateriasInscriptas;
    private javax.swing.JRadioButton jrMateriasNoInscriptas;
    private javax.swing.JTable jtInscripcion;
    // End of variables declaration//GEN-END:variables

    private void cabecera() {

        jInscripcion.addColumn("ID");
        jInscripcion.addColumn("Nombre");
        jInscripcion.addColumn("Año");
        jtInscripcion.setModel(jInscripcion);

    }

    private void armarComboB() {
        alumnos = ad.listarAlumnos();

        for (Alumno alumno : alumnos) {
            jcAlumnoSeleccionado.addItem(alumno);
        }
    }

    private void borrarFilas() {
        int f = jtInscripcion.getRowCount() - 1;

        for (; f >= 0; f--) {
            jInscripcion.removeRow(f);
        }
    }
}
